[CUDA_Runtime_jll]
__clear__ = ["version", "local"]
local = "true"
version = "13.0"

[MPIPreferences]
__clear__ = ["preloads_env_switch"]
_format = "1.0"
abi = "MPICH"
binary = "system"
cclibs = []
libmpi = "/software/petsc-mpich-cuda/lib/libmpi.so"
mpiexec = "/software/petsc-mpich-cuda/bin/mpiexec"
preloads = []
preloads_env_switch = "MPICH_GPU_SUPPORT_ENABLED"
